ALTER TABLE users
    ADD COLUMN app_publish_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN app_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN address VARCHAR(255) DEFAULT '',
    ADD COLUMN sign VARCHAR(255) DEFAULT '',
    ADD COLUMN status INT NOT NULL DEFAULT 1,
    ADD COLUMN code VARCHAR(255) DEFAULT '',
    ADD COLUMN twitter VARCHAR(255) DEFAULT '',
    ADD COLUMN telegram VARCHAR(255) DEFAULT '',
    ADD COLUMN discord VARCHAR(255) DEFAULT '';
