version: '3.8'

services:
  # postgres:
  #   image: postgres:14
  #   container_name: hajime_postgres_container
  #   environment:
  #     POSTGRES_USER: hajime
  #     POSTGRES_PASSWORD: hajime
  #     POSTGRES_DB: hajime
  #   restart: always
  #   ports:
  #     - "0.0.0.0:5435:5432"
  #   volumes:
  #     - ./docker-data/postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - hajime

  hajime:
    image: hajime_center:v2.0
    build:
      context: .
    container_name: hajime_center_container
    privileged: true
    restart: always
    # ports:
    #   - "0.0.0.0:8000:8000"
    #   - "0.0.0.0:8001:8001"
    volumes:
      - ./app.env:/srv/HajimeCenter/app.env
      - ./logs:/srv/HajimeCenter/logs
      - ./storage:/srv/storage
    # networks:
    #   - hajime
    network_mode: "host"
    # depends_on:
    #   - postgres

# networks:
#   hajime:
#     driver: bridge
